- hosts: allnode
  remote_user: root
  roles:
    - 01-initialize

- hosts: deployer
  remote_user: root
  tasks:
    
  - name: download cfssl
    get_url: 
      url: https://pkg.cfssl.org/R1.2/cfssl_linux-amd64
      dest: /usr/local/bin/cfssl
      mode: 0555

  - name: download cfssljson
    get_url: 
      url: https://pkg.cfssl.org/R1.2/cfssljson_linux-amd64
      dest: /usr/local/bin/cfssljson
      mode: 0555

  - name: download cfssl-certinfo
    get_url: 
      url: https://pkg.cfssl.org/R1.2/cfssl-certinfo_linux-amd64
      dest: /usr/local/bin/cfssl-certinfo
      mode: 0555

  - name: copy ca config file
    copy:
      src: roles/01-initialize/files/ca-gen.sh
      dest: /tmp/ca-gen.sh
      mode: 0555

  - name: gemerate ca work directory
    file:
      path: /opt/k8s/work
      state: directory
      mode: "u=rwx,g=rwx,o=rwx"

  - name: generate ca config files
    command: /bin/bash /tmp/ca-gen.sh

  - name: generate CA
    command: "cd /opt/k8s/work && cfssl gencert -initca /opt/k8s/work/ca-csr.json | cfssljson -bare ca"

