---
- name: create directory
  file:
    path: /ops/k8s/bin
    state: directory
    mode: "u=rwx,g=rwx,o=rwx"
- name: upload environment.sh
  copy: src=../files/environment.sh dest=/ops/k8s/bin/environment.sh mode=755
- name: upload pre-initialize.sh
  copy: src=../files/initialize.sh dest=/tmp/initialize.sh mode=755
- name: set up servers
  shell: /tmp/initialize.sh
